config/routes.rb
PrintThing::Application.routes.draw do
  resources :prints, only: [:new, :show, :create, :index, :destroy] do
    resources :steps, only: [:show, :update], controller: 'print/steps'
  end

  root to: 'prints#index'
  
  get 'user/:id' => 'users#show'
  get 'signup' => 'users#new'
  resources :users
  
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'impression/:id' => 'prints#show'
  get 'edit/:id' => 'users#edit'
  
  
 
  resources :home_page

  resources :charges

end

app/models/print.rb
class Print < ActiveRecord::Base
  cattr_accessor :form_steps do
    %w(attachment finition confirm)
  end

  attr_accessor :form_step

  validates :attachment, presence: true, if: -> { required_for_step?(:attachment) }
  validates :materiau, :qualite, :livraison, presence: true, if: -> { required_for_step?(:finition) }
  validates :address, :town, :departement, :zipcode, :pays, :useridentifiant, presence: true, if: -> { required_for_step?(:confirm) }


  def required_for_step?(step)
    return true if form_step.nil?
    return true if self.form_steps.index(step.to_s) <= self.form_steps.index(form_step)
  end

  mount_uploader :attachment, AttachmentUploader

end

app/models/user.rb
class User < ActiveRecord::Base


  has_many :prints

  has_secure_password

  def owner?
    self.role == 'owner'
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  
  def current_user
    @current_user ||=
      User.find(session[:user_id]) if
    session[:user_id]
  end
    
    
  def require_user
     redirect_to '/login' unless
     current_user
   end

   def current_print
     @current_print ||=
       Print.find(params[:name]) if 
       params[:name]
   end


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  attr_accessor :volume
  attr_accessor :name
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end
  
  def create 
    #Amount in cent
  
    @amount = 50000000
    
    
    customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :card => params[:stripeToken]
    ) 
    
    charge = Stripe::Charge.create(
    :customer   => customer.id,
    :amount     => @amount,
    :description=> 'Rails Stripe customer',
    :currency   => 'usd',
    )
    redirect_to '/prints/78/steps/attachment'
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to @print

  end







end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  
  def index
    
  end
  
  
  def show
    
  end


end

app/controllers/print/steps_controller.rb
class Print::StepsController < ApplicationController
  include Wicked::Wizard
steps *Print.form_steps
  
  def show
    @print = Print.find(params[:print_id])
    render_wizard
  end
  
  def update
    @print = Print.find(params[:print_id])
    @print.update(print_params(step))
    render_wizard @print
  end
  
  private
  
  def print_params(step)
    permitted_attributes = case step
                           when "attachment"
                             [:attachment]
                           when "finition"
                             [:materiau, :qualite, :livraison, :name]
                           when "confirm"
                             [:address, :town, :departement, :zipcode, :pays, :useridentifiant]
                           end
    
    params.require(:print).permit(permitted_attributes).merge(form_step: step)
  end
  
  end
  
  
  
  

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  before_action :set_print, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only:  [:index, :show, :new, :create, :destroy]
  # GET /prints
  # GET /prints.json
  def index
    # Normally you'd have more complex requirements about
    # when not to show rows, but we don't show any records that don't have a name
    
    @prints = Print.where(:useridentifiant => session[:user_id])
 
    end


  # GET /prints/1
  # GET /prints/1.json
  def show
  @print = Print.find(params[:id])
  @user = User.find(current_user)
  end

  # GET /prints/new
  def new
    @print = Print.new
  end

  # POST /prints
  # POST /prints.json
  def create
    @print = Print.new
    @print.save(validate: false)
    redirect_to print_step_path(@print, Print.form_steps.first)
    
    
  end

  # DELETE /prints/1
  # DELETE /prints/1.json
  def destroy
    @print.destroy
    respond_to do |format|
      format.html { redirect_to prints_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_print
      @print = Print.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def print_params
      params.require(:print).permit(:attachment, :materiau, :qualite, :livraison, :address, :town, :departement, :zipcode, :pays, :useridentifiant, :name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  
  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && 
      @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    
    
    end
  end



  def destroy
  session[:user_id] = nil
  redirect_to '/' 
  end
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end


  def show
      @user = User.find(params[:id])
  end
  
  
  def edit
      @user = User.find(params[:id])
     
  end
  
  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
              redirect_to @user
            else
              render 'edit'
            end
  end


  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end



  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :address2, :town2, :zipcode2, :pays2)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/print/steps_helper.rb
module Print::StepsHelper
end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Upload</title>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <!-- Bloc pour l'animation avec la vue de la page -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.3/velocity.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.3/velocity.ui.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenMax.min.js"></script>
   
     <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/1.3.0/jquery.scrollmagic.js"></script>
 	<script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/1.3.0/jquery.scrollmagic.debug.js"></script><br />	
	
   <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.0/plugins/animation.gsap.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.0/plugins/debug.addIndicators.js"></script>
     <!-- Fin du bloc -->
  

  <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r73/three.min.js"></script>
  
  
  <%= stylesheet_link_tag    "application","data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
 
  <%= csrf_meta_tags %>





		<script>
		$(function(){
		    $("#attachment").change(function(){
		        $("#form1").submit();
		    });
		});
		
		</script>











 

 
 
 
  <script type="text/javascript" src="app.js"></script> 
  <script type="text/javascript">
  $(function(){
      $("#attachment").change(function(){
          $("#form1").submit();
      });
  });
  </script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/VelocityJS/1.2.2/VelocityJS.ui.js"></script>

<link rel="stylesheet" href="animsition.min.css">




<script>
$(document).ready(function(){
document.querySelector( "#nav-toggle" )
	.addEventListener( "click", function() {
	  this.classList.toggle( "active" );
   });
});

</script>


</head>

<body style="position:relative;">


 <div class="menu">
	 <div style="margin:0 auto;margin-top:40px; margin-left:85px;margin-bottom:30px;">
      <h1 style="color:white;font-size:27px; letter-spacing:6px; margin: 0 auto;font-family:'San Francisco'; font-weight:200; ">FABRIK</h1>
  </div>
      <!-- Menu -->
      <ul>
        <li><%= link_to 'Dashboard', '/' %></li>
        <li><%= link_to 'New print',  prints_path, method: :create %></li>
        <li><%= link_to 'Store', '/' %></li>
        <li><%= link_to 'Préferences', current_user %></li>
      </ul>
	  
	  
	  <div style="position:absolute; bottom:20px; left:55px;bottom:40px;"><%= image_tag("Signaturefinal.svg", :alt => "images") %></div>
	  <div style="position:absolute; bottom:20px; left:98px;bottom:33px;"><h5 style="letter-spacing:6px; font-size:11px;color:white;">v 12-0-5</h1></div>
    </div>












    <!-- Header -->
      <div class="jumbotron" style="z-index:15;">

        <div class="icon-menu">
          <a id="nav-toggle"><span></span></a>
        </div>
			
		
   		<!-- Nom utilisateur déclenche menu -->

    	<div class="dropdown-toggle" style="position:absolute; right:40px; top:50px; z-index:5;background-color:none;">
       	 <% if current_user %> 

      	 		<a style="font-family: 'San Francisco'; font-size:18px; float:left; display:inline; color:black;"> <%= current_user.last_name %> <%= current_user.first_name %> <div style="margin-left:8px; margin-top:-1px; width:16px; height:16px; float:right; 				display:inline;"><%= image_tag("triangle.svg", :alt => "images") %></div></a>

   	   		 <% else %> 

       			<%= link_to "Login", 'login' %></a></li> 
       			<%= link_to "Signup", 'signup' %></a></li> 

   	   		 <% end %>
      
    	 </div>
	
	<script>
	 var btn = $("#tweenBtn"),
	    toggle = $(".legend-child"),
	    isOpen = true;
	//record the height of the elment in its open state
	toggle.data("height", toggle.height());
	console.log($(this).data("height"));

	btn.click(function(){
	  if (isOpen==false) {
	    TweenMax.to($(toggle), 1, {height:$(toggle).data("height")})
	    isOpen=true
	    }else{
	      TweenMax.to($(toggle), 1, {height:10});
	      isOpen=false
	    }
	})
	
	</script>
	
</div>







<%= yield %>







 <script>

   /* Push the body and the nav over by 285px over */
 	var toggle = false;

	
   $(".icon-menu").click( function() {
	   
	   
 	  if (toggle == false) {
	  
 		  TweenLite.to(".menu", 1.2, { x:0,ease:Power4.easeOut});
		  TweenLite.to("body", 1.2, { x:285,ease:Power4.easeOut});
 		 


	
 	toggle = true;
	
 	 } else {
		  
		  TweenLite.to(".menu", 1.2, { x:0,ease:Power4.easeOut});
	      TweenLite.to("body", 1.2, { x:0,ease:Power4.easeOut});
 		
		  
 		toggle = false;
 	}
		
   });

   /* Then push them back */




 $(document).ready(function(){
 	document.querySelector( "#nav-toggle" ).addEventListener( "click", function() {
 	  this.classList.toggle( "active" );
    });
 });






 $(document).ready(main);

 
 
 </script>
















</body>
</html>

app/views/print/steps/payment.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Prix : <%= @print.name%>,99 €</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js"></script>

  <button id="customButton" class="btnbas btn-2 btn-2c">Purchase</button>

  <%= javascript_tag do %>
    var handler = StripeCheckout.configure({
      key: 'pk_test_msnYHle51XAqqvu3xDHBaioL',
      image: '/img/documentation/checkout/marketplace.png',
      locale: 'auto',
      token: function(token) {
        // Use the token to create the charge with a server-side script.
        // You can access the token ID with `token.id`
      }
    });

    $('#customButton').on('click', function(e) {
      // Open Checkout with further options
      handler.open({
        name: 'fabrik.company',
        description: 'Impression ',
        currency: "eur",
        amount: <%= @print.name %>99
      });
      e.preventDefault();
    });

    // Close Checkout on page navigation
    $(window).on('popstate', function() {
      handler.close();
    });
	
	token: function(response) {
	  var tokenInput = $("<input type=hidden name=stripeToken />").val(response.id);
	  var emailInput = $("<input type=hidden name=stripeEmail />").val(response.email);
	  $("form").append(tokenInput).append(emailInput).submit();
	}
	
	
  <% end %>
	



<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Prix : <%= @print.name%>,99 €</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @print.name%>99"
          data-locale="auto"></script>
<% end %>	
	

<% end %>

app/views/prints/_form.html.erb
<%= form_for(@print) do |f| %>
  <% if @print.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@print.errors.count, "error") %> prohibited this print from being saved:</h2>

      <ul>
      <% @print.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.text_field :attachment %>
  </div>
  <div class="field">
    <%= f.label :materiau %><br>
    <%= f.text_field :materiau %>
  </div>
  <div class="field">
    <%= f.label :qualite %><br>
    <%= f.text_area :qualite %>
  </div>
  <div class="field">
    <%= f.label :livraison %><br>
    <%= f.text_area :livraison %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prints/edit.html.erb
<h1>Editing perint</h1>

<%= render 'form' %>

<%= link_to 'Show', @print %> |
<%= link_to 'Back', prints_path %>

app/views/prints/index.html.erb
<div style="text-align: center; width:100%; position:relative; margin:0 auto;height:80%; background-color:white; padding-top:50px;" id="content">
	<div style="width:680px;position:relative; margin: 0 auto;">
	<h1 class="fadeIn" style="color:black; font-size:32px; margin-top:-8px;float:left; display:block; margin-bottom:00px;letter-spacing:2px;">IMPRESSIONS</h1>
	<h1 style="color:#545454; font-size:36px;float:left; display:block; margin-bottom:00px;font-size:15px;letter-spacing:0.5px;margin-left:0px;font-weight:100;position:absolute;margin-top:39px; border-radius:5px;padding: 4px 10px;background-color:#F2F2F2;">Actualisé à <%= Time.now.strftime("%H:%M")%> - <%= Time.now.strftime("%m/%d") %></h1>
	

	
<br>
<br>
<div style="float:right; display:inline;margin-top:-50px;margin-right:-30px;margin-left:-1080px;" id="content">
<%= link_to 'New print', prints_path, method: :new, :class => 'btnprint btn-2print btn-2cprint' %>
</div>

<div style="float:right; display:inline; margin-top:-20px; margin-right:-390px;width:28px; height:18px;position:absolute; width:120px;">
	
	
	
	
		<div id="rangement" style="position:absolute; right:0; width:120px; height:27px;border-radius:18px; border:1px solid #454CDC;float:right">
			<div id="rrond" style="width:15px; height:15px; background-color:#FE9321; border-radius:80%; 			float:right;margin-top:5px;margin-right:7px;opacity:1.5;"></div>
			<h5 id="texteetat" style="margin-top:5px; margin-bottom:0px;margin-left:0px; margin-right:8px; float:right;font-size:13px;letter-spacing:0px;font-weight:300;color:#787878">ready to print</h5>
		</div>
	
</div>
</div>






	<script>
	
	
	/* Setup variables */
		
		   var tl70;

		   // Controller
		   var controller70 = new ScrollMagic();


	   /* Create a timeline */
	   tl70 = new TimelineMax();
	   
	   

	  
	 
	   tl70.set("#rangement",  { width:30, borderColor:'#ffffff'});
	   tl70.set("#texteetat", { opacity:0});
	   tl70.set("#texteetat",{text:"Loading"});
	   tl70.set("#texteetat",{text:"Ready to print"}, 6.5);
		 
  	 
	   
		 tl70.to("#rangement", 1.5, { borderColor:'#787878',  ease:Power4.easeOut}, 1.9)
	         .to("#rrond", 0.8, { backgroundColor:'#FE9321',  ease:Power4.easeOut}, 1)
	         .to("#rrond", 0.8, { backgroundColor:'#F60109',  ease:Power4.easeOut}, 1.8)
	         .to("#rrond", 0.8, { backgroundColor:'#FE9321',  ease:Power4.easeOut}, 2.6)
	         .to("#rrond", 0.8, { backgroundColor:'#F60109',  ease:Power4.easeOut}, 3.4)
	         .to("#rrond", 0.8, { backgroundColor:'#FE9321',  ease:Power4.easeOut}, 4.2)
	         .to("#rrond", 0.8, { backgroundColor:'#F60109',  ease:Power4.easeOut}, 5)
	         .to("#rrond", 0.8, { backgroundColor:'#FE9321',  ease:Power4.easeOut}, 5.8)
	         .to("#rrond", 0.8, { backgroundColor:'#F60109',  ease:Power4.easeOut}, 6.6)
	         .to("#rrond", 2, { backgroundColor:'#00AD43',  ease:Power4.easeOut}, 7.4)
	   
		     .to("#rangement", 1.5, { width:90,  ease:Power4.easeOut}, 2)
	         .to("#texteetat", 2, { opacity:1, ease:Power4.easeOut},2.5)
		     .to("#texteetat", 0.2, { opacity:0, ease:Power4.easeOut}, 5)
		     .to("#rangement", 1.5, { width:30,  ease:Power4.easeOut}, 5)
	         .to("#rangement", 1, {borderColor:'#ffffff',  ease:Power4.easeOut}, 5.6)
	      
	         .to("#rangement", 1.5, { borderColor:'#787878',  ease:Power4.easeOut}, 6.4)
		     .to("#rangement", 1.5, { width:120,  ease:Power4.easeOut}, 6.6)
	         .to("#texteetat", 2, { opacity:1, ease:Power4.easeOut},7.6)
		     .to("#texteetat", 0.2, { opacity:0, ease:Power4.easeOut}, 10.6)
		     .to("#rangement", 1.5, { width:30,  ease:Power4.easeOut}, 10.6)
	         .to("#rangement", 1, {borderColor:'#ffffff',  ease:Power4.easeOut}, 11.6)
			 
	   .add("end");
	   
	   
	   
	   
	   
	       
	       
	   
	   
	   var scene = new ScrollScene({triggerElement: "#Calque_8"})
	       .addTo(controller70)
	       .setTween(tl70);
	   
	   
		   scene.addIndicators();
	 	  	
		   scene.reverse(false);
		   
	 	 
 
	</script>
	






<div style="width:680px; text-align:center; background-color:white;  margin: 0 auto; margin-top:20px; margin-bottom:20px;border-radius:5px; padding:60px;padding-top: 30px; padding-bottom:px; ">
<div style="width:680px; text-align:center; background-color:white;  margin: 0 auto; margin-top:0px; margin-bottom:0px;">
<table style="width:100%;">
<table style="width:100%; ">
  <thead>
    <tr>
      <th style="width:30px;">ID</th>
      <th style="width:143px;">Nom</th>
      <th style="width:113px;">Materiau</th>
      <th style="width:115px;">Qualité</th>
      <th style="width:120px;">Prix</th>
      <th></th>

    </tr>
  </thead>
</table>

  <tbody style="display: block;  height:400px; overflow: auto; width:100%; position:relative;">
	  <table style=" display:block; height:440px; overflow-y: scroll; width:100%" id="tableid">
  		
	  	<div id="welcomeDiv" style="width:680px; height:380px; background-color:#F2F2F2;display:none;position:absolute;top:198px;margin: 0 auto;border-radius:5px;text-align:center;">
	  		<div style="width:150px; height:150px;margin: 0 auto;margin-top:50px;"><%= image_tag("logook.svg", :alt => "images") %></div>
	  		<h1 style="font-size:25px; letter-spacing:1px;margin-top:25px;">Prêt à imprimer</h1>
	  		<div style="width:450px;margin: 0 auto;margin-top:15px;letter-spacing:0.5px;"><p style="letter-spacing:0.5px">Toutes vos impressions s'afficheront ici.</p>
	  		<p style="margin-top:10px;line-height:20px;letter-spacing:0.5px">Vous n'avez pas encore lancé d'impression. Lancez votre <strong>première impression</strong> avec le bouton en haut à droite <strong>"New print"</script>.</p></div>
		
		
		
	  	</div>
		  
	<% @prints.each do |print| %>
     
		 <tr id="stay" class="tam" style="width:100%; max-height:40px;" data-link="prints/<%= print.id %>" >
		  
        <td style="width:40px;"><%= print.id %></td>
        <td style="width:160px;font-weight:300;"><%=File.basename(print.attachment.path)%></td>
        <td style="width:170px;color:grey;"><%= print.materiau %></td>
		<td style="width:100px;color:grey;"><%= print.qualite %></td>
		<td style="width:100px;text-align:right;padding-right:15px;"><%= print.name %> €</td>
        <td style="width:220px;"><div class="progressBar2"><div></div></div></td>
		
		
		
		<%= javascript_tag do %>
		jQuery(function($) {
		$("tr[data-link]").click(function() {
		window.location = this.dataset.link
		});
		})
		
		<% end%>
		
	
		
		
	
		
		<script>
		function progress(percent, $element) {
		    var progressBarWidth = percent * $element.width() / 100;
		    $element.find('div').animate({ width: progressBarWidth }, 500).html(percent + "% ");
		}
	
		progress(100, $('.progressBar2'));
		</script>
	
	 </tr>
    <% end %>

	
	
  </tbody>
</table>
</table>
</div>


</div>
<div class="bottomnew" style="background-color:white">
	<div style="margin: 0 auto;width:780px;">
		<p style="color:black; font-size:15px;letter-spacing:2px;font-weight:200;float:left; position:inline; margin-top:8px; margin-left:0px;">FABRIK</p> 
		<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">-</p>
		<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">Conditions générales</p>
		<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">-</p>
		<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">Politique de confidentialité</p>
		<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">-</p>
		<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">Politique relative au contenu</p>
		<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">-</p>
		
			<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">Copyright © 2015 Fabrik</p>
			<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">-</p>
			<p style="color:black; font-size:12px;letter-spacing:0px;font-weight:200;float:left; position:inline; margin-left:8px;margin-top:8px;">Tous droits réservés</p>
	</div>
			
	</div>
</div>
</div>






<script>
$(document).ready(function(){
document.querySelector( "#nav-toggle" )
	.addEventListener( "click", function() {
	  this.classList.toggle( "active" );
   });
});

</script>

	<script>
		$(document).ready(function(){
		var myElem = document.getElementById('stay');
		if (myElem === null) { 
		 document.getElementById('welcomeDiv').style.display = "block";
			
		}
		
	});
		
		</script>	
	
	
	
	
		
	

app/views/prints/new.html.erb
<h1>New print</h1>

<%= render 'form' %>

<%= link_to 'Back', prints_path %>